Repository GOSOPT-CDS-BAEMIN/Android, pull requests merged in 2023-05, with the labels that each got.

#6 #1 [chore] 프로젝트 기초 세팅 변경
  app/build.gradle
  app/src/main/java/com/sopt/baemin/data/api/ApiFactory.kt
  app/src/main/java/com/sopt/baemin/data/model/request/RequestDto.kt
  app/src/main/java/com/sopt/baemin/data/model/response/BaseResponse.kt
  app/src/main/java/com/sopt/baemin/data/model/response/ResponseDto.kt
  app/src/main/java/com/sopt/baemin/data/service/ExampleService.kt
  app/src/main/java/com/sopt/baemin/presentation/MainActivity.kt
  app/src/main/java/com/sopt/baemin/util/binding/BindingActivity.kt
  app/src/main/java/com/sopt/baemin/util/binding/BindingFragment.kt
  app/src/main/java/com/sopt/baemin/util/extension/ActivityExt.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: chore 🧹

#11 #8 [ui/server] Feature/menu detail
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/baemin/data/api/ApiFactory.kt
  app/src/main/java/com/sopt/baemin/data/model/response/MenuDetailResponse.kt
  app/src/main/java/com/sopt/baemin/data/service/MenuDetailService.kt
  app/src/main/java/com/sopt/baemin/presentation/MainActivity.kt
  app/src/main/java/com/sopt/baemin/presentation/menu_detail/MenuDetailActivity.kt
  app/src/main/res/drawable/box_layout.xml
  app/src/main/res/drawable/btn_layout.xml
  app/src/main/res/drawable/ic_food_baoza.png
  app/src/main/res/drawable/ic_minus.xml
  app/src/main/res/drawable/ic_more_btn.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_warn.xml
  app/src/main/res/layout/activity_menu_detail.xml
  app/src/main/res/values/themes.xml
Labels: feat ✨, 주영

#12 #9 [ui/server] Feature/review filter
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/baemin/data/api/ApiFactory.kt
  app/src/main/java/com/sopt/baemin/data/model/response/FoodResponse.kt
  app/src/main/java/com/sopt/baemin/data/service/FoodListReviewService.kt
  app/src/main/java/com/sopt/baemin/presentation/MainActivity.kt
  app/src/main/java/com/sopt/baemin/presentation/bottomsheet/BottomSheetActivity.kt
  app/src/main/java/com/sopt/baemin/presentation/bottomsheet/InitBottomSheetActivity.kt
  app/src/main/res/drawable/checkbox_custom.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_new_opt.xml
  app/src/main/res/drawable/ic_uncheck.xml
  app/src/main/res/layout/activity_review_filter.xml
  app/src/main/res/layout/activity_show_review.xml
  app/src/main/res/values/strings.xml
Labels: feat ✨, 주영

#7 #3 [ui/server] store detail
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/baemin/data/api/ApiFactory.kt
  app/src/main/java/com/sopt/baemin/data/model/response/BaseResponse.kt
  app/src/main/java/com/sopt/baemin/data/model/response/MenuResponse.kt
  app/src/main/java/com/sopt/baemin/data/model/response/ResponseGetReviewFilterFoodDto.kt
  app/src/main/java/com/sopt/baemin/data/model/response/ReviewResponse.kt
  app/src/main/java/com/sopt/baemin/data/service/MenuService.kt
  app/src/main/java/com/sopt/baemin/data/service/ReviewService.kt
  app/src/main/java/com/sopt/baemin/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/baemin/presentation/detail/DetailAdapter.kt
  app/src/main/java/com/sopt/baemin/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/sopt/baemin/presentation/detail/menu/MenuBestAdapter.kt
  app/src/main/java/com/sopt/baemin/presentation/detail/menu/MenuFragment.kt
  app/src/main/java/com/sopt/baemin/presentation/detail/review/ReviewAdapter.kt
  app/src/main/java/com/sopt/baemin/presentation/detail/review/ReviewFragment.kt
  app/src/main/java/com/sopt/baemin/util/OnSingleClickListener.kt
  app/src/main/java/com/sopt/baemin/util/binding/BindingAdapter.kt
  app/src/main/java/com/sopt/baemin/util/extension/ContentExt.kt
  app/src/main/res/drawable/ic_baemin_back.xml
  app/src/main/res/drawable/ic_baemin_cart.xml
  app/src/main/res/drawable/ic_baemin_home.xml
  app/src/main/res/drawable/ic_detail_back.xml
  app/src/main/res/drawable/ic_detail_bar.xml
  app/src/main/res/drawable/ic_detail_cart.xml
  app/src/main/res/drawable/ic_detail_download.xml
  app/src/main/res/drawable/ic_detail_home.xml
  app/src/main/res/drawable/ic_detail_info.xml
  app/src/main/res/drawable/ic_detail_menu_down.xml
  app/src/main/res/drawable/ic_detail_review_filter.xml
  app/src/main/res/drawable/ic_detail_review_rate.xml
  app/src/main/res/drawable/ic_detail_review_recommend.xml
  app/src/main/res/drawable/ic_detail_tooltip.xml
  app/src/main/res/drawable/iv_detail_coupon.png
  app/src/main/res/drawable/iv_detail_food.png
  app/src/main/res/drawable/iv_detail_image.png
  app/src/main/res/drawable/iv_detail_review_main.png
  app/src/main/res/drawable/iv_detail_review_star.png
  app/src/main/res/drawable/iv_detail_review_sub.png
  app/src/main/res/drawable/iv_detail_star.png
  app/src/main/res/drawable/iv_review_profile.png
  app/src/main/res/drawable/shape_black80fill_24_rect.xml
  app/src/main/res/drawable/shape_gray1fill_16_rect.xml
  app/src/main/res/drawable/shape_gray2fill_40_rect.xml
  app/src/main/res/drawable/shape_gray2fill_gray4line_0_rect.xml
  app/src/main/res/drawable/shape_gray5fill_29_rect.xml
  app/src/main/res/drawable/shape_sub4fill_3_rect.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/item_detail_menu.xml
  app/src/main/res/layout/item_detail_menu_best.xml
  app/src/main/res/layout/item_detail_review.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: feat ✨, 하정
